import cv2
import numpy as np
import torch

def postprocess(image: torch.tensor) -> np.ndarray:    
    """
    Postprocessing function for the images generated by the Tumor Generator.

    Args:
        image (ndarray): Input image, should be a 3-channel image tensor.
    Returns:
        ndarray: A 1-channel grayscale image with the same height and width as the input image.
    """
    samples = image.cpu().numpy().clip(0, 255).astype(np.uint8)    
    
    image = cv2.cvtColor(samples, cv2.COLOR_BGR2GRAY)
    image = cv2.equalizeHist(image)

    return image